require 'spec_helper'

# We have to test auditd::config via auditd, because auditd::config is
# private.  To take advantage of hooks built into puppet-rspec, the
# class described needs to be the class instantiated, i.e., auditd.
# This test also includes tests for private class auditd::config::logging

describe 'auditd' do
  # Every file this module declares in /etc/audit/rules.d with the default
  # (simp) profile; see $auditd::config::rule_file_attributes for why these
  # must carry owner/group/mode themselves.
  RULES_D_FILES = [
    '/etc/audit/rules.d/00_head.rules',
    '/etc/audit/rules.d/05_default_drop.rules',
    '/etc/audit/rules.d/99_tail.rules',
    '/etc/audit/rules.d/50_00_simp_base.rules',
    '/etc/audit/rules.d/75.audit_auditd_config.rules',
  ].freeze

  context 'supported operating systems' do
    on_supported_os.each do |os, os_facts|
      context "on #{os}" do
        let(:facts) { os_facts }

        context 'with default parameters' do
          let(:params) { {} }

          it { is_expected.to compile.with_all_deps }
          it {
            is_expected.to contain_file('/etc/audit/rules.d').with(
              ensure: 'directory',
              owner: 'root',
              group: 'root',
              mode: 'u+rwX,g-rwx,o-rwx',
              recurse: true,
              purge: true,
              force: true,
            )
          }
          # /etc/audit/audit.rules and .prev are generated by augenrules;
          # their permissions are unmanaged by default (the audit_rules_*
          # parameters default to undef) so Puppet does not fight augenrules
          ['/etc/audit/audit.rules', '/etc/audit/audit.rules.prev'].each do |f|
            it { is_expected.to contain_file(f).without_owner }
            it { is_expected.to contain_file(f).without_group }
            it { is_expected.to contain_file(f).without_mode }
          end
          it {
            is_expected.to contain_file('/etc/audit').with(
              ensure: 'directory',
              owner: 'root',
              group: 'root',
              mode: 'u+rwX,g-rwx,o-rwx',
              recurse: true,
              purge: true,
              force: true,
            )
          }
          RULES_D_FILES.each do |f|
            it {
              is_expected.to contain_file(f).with(
                owner: 'root',
                group: 'root',
                mode: 'u+rwX,g-rwx,o-rwx',
              )
            }
          end
          it { is_expected.not_to contain_augeas('auditd/USE_AUGENRULES') }
          it { is_expected.not_to contain_class('auditd::config::logging').that_notifies('Class[auditd::service]') }
          it {
            is_expected.to contain_file('/var/log/audit').with(
              ensure: 'directory',
              owner: 'root',
              group: 'root',
              mode: 'u+rX,g-rwx,o-rwx',
              recurse: true,
            )
          }
          it { is_expected.to contain_class('auditd::config::audit_profiles') }
          it { is_expected.to contain_class('auditd::config::audit_profiles::simp') }
          it { is_expected.not_to contain_class('auditd::config::audisp') }
          it { is_expected.not_to contain_class('auditd::config::audisp::syslog') }
        end # Default params

        context 'with audit_rules_* parameters set' do
          let(:params) do
            {
              audit_rules_owner: 'root',
              audit_rules_group: 'root',
              audit_rules_mode: '0600',
            }
          end

          ['/etc/audit/audit.rules', '/etc/audit/audit.rules.prev'].each do |f|
            it {
              is_expected.to contain_file(f).with(
                owner: 'root',
                group: 'root',
                mode: '0600',
              )
            }
          end
        end

        context 'with purge behaviour false' do
          let(:params) { { purge_auditd_rules: false } }

          it { is_expected.to compile.with_all_deps }
          it {
            is_expected.to contain_file('/etc/audit/rules.d').with(
              ensure: 'directory',
              owner: 'root',
              group: 'root',
              mode: 'u+rwX,g-rwx,o-rwx',
              recurse: true,
              purge: false,
              force: true,
            )
          }
        end

        # custom_spec.rb drives auditd::config::audit_profiles::custom through a
        # stubbed auditd::config, so it can only prove the splat is wired -- it
        # cannot catch a regression in the real $rule_file_attributes. Exercise
        # the custom profile through the real class here so the actual
        # owner/group/mode are pinned.
        context "with default_audit_profiles ['custom']" do
          let(:params) { { default_audit_profiles: ['custom'] } }
          let(:hieradata) { 'custom_audit_profile/rules' }

          it { is_expected.to compile.with_all_deps }
          it {
            is_expected.to contain_file('/etc/audit/rules.d/50_00_custom_base.rules').with(
              owner: 'root',
              group: 'root',
              mode: 'u+rwX,g-rwx,o-rwx',
            )
          }

          context 'with a non-root config_group' do
            let(:params) { { default_audit_profiles: ['custom'], config_group: 'rspec' } }

            it {
              is_expected.to contain_file('/etc/audit/rules.d/50_00_custom_base.rules').with(
                owner: 'root',
                group: 'rspec',
                mode: 'u+rwX,g+rX,g-w,o-rwx',
              )
            }
          end
        end

        context 'with empty default_audit_profiles' do
          let(:params) { { default_audit_profiles: [] } }

          it { is_expected.to compile.with_all_deps }
          it { is_expected.not_to contain_class('auditd::config::audit_profiles') }
        end

        context 'with different log_group' do
          let(:params) { { log_group: 'rspec' } }

          it { is_expected.to compile.with_all_deps }
          # config_group defaults to log_group so existing deployments that
          # set only log_group retain their pre-config_group /etc/audit
          # ownership.
          it {
            is_expected.to contain_file('/etc/audit').with(
              ensure: 'directory',
              owner: 'root',
              group: 'rspec',
              mode: 'u+rwX,g+rX,g-w,o-rwx',
              recurse: true,
              purge: true,
              force: true,
            )
          }
          it {
            is_expected.to contain_file('/etc/audit/rules.d').with(
              ensure: 'directory',
              owner: 'root',
              group: 'rspec',
              mode: 'u+rwX,g+rX,g-w,o-rwx',
              recurse: true,
              purge: true,
              force: true,
            )
          }
          # audit.rules/.prev permissions are unmanaged regardless of
          # config_group (augenrules owns them; see the audit_rules_* params)
          ['/etc/audit/audit.rules', '/etc/audit/audit.rules.prev'].each do |f|
            it { is_expected.to contain_file(f).without_group }
          end

          RULES_D_FILES.each do |f|
            it {
              is_expected.to contain_file(f).with(
                owner: 'root',
                group: 'rspec',
                mode: 'u+rwX,g+rX,g-w,o-rwx',
              )
            }
          end

          it {
            is_expected.to contain_file('/etc/audit/auditd.conf').with(
              owner: 'root',
              group: 'rspec',
              mode: 'u+rwX,g+rX,g-w,o-rwx',
            )
          }

          it {
            is_expected.to contain_file('/var/log/audit').with(
              ensure: 'directory',
              owner: 'root',
              group: 'rspec',
              mode: 'u+rX,g+rX,g-w,o-rwx',
              recurse: true,
            )
          }
        end

        context 'with different config_group' do
          let(:params) { { config_group: 'rspec' } }

          it { is_expected.to compile.with_all_deps }
          it {
            is_expected.to contain_file('/etc/audit').with(
              ensure: 'directory',
              owner: 'root',
              group: 'rspec',
              mode: 'u+rwX,g+rX,g-w,o-rwx',
              recurse: true,
              purge: true,
              force: true,
            )
          }
          it {
            is_expected.to contain_file('/etc/audit/rules.d').with(
              ensure: 'directory',
              owner: 'root',
              group: 'rspec',
              mode: 'u+rwX,g+rX,g-w,o-rwx',
              recurse: true,
              purge: true,
              force: true,
            )
          }
          # audit.rules/.prev permissions are unmanaged regardless of
          # config_group (augenrules owns them; see the audit_rules_* params)
          ['/etc/audit/audit.rules', '/etc/audit/audit.rules.prev'].each do |f|
            it { is_expected.to contain_file(f).without_group }
          end

          RULES_D_FILES.each do |f|
            it {
              is_expected.to contain_file(f).with(
                owner: 'root',
                group: 'rspec',
                mode: 'u+rwX,g+rX,g-w,o-rwx',
              )
            }
          end

          it {
            is_expected.to contain_file('/etc/audit/auditd.conf').with(
              owner: 'root',
              group: 'rspec',
              mode: 'u+rwX,g+rX,g-w,o-rwx',
            )
          }

          it {
            is_expected.to contain_file('/var/log/audit').with(
              ensure: 'directory',
              owner: 'root',
              group: 'root',
              mode: 'u+rX,g-rwx,o-rwx',
              recurse: true,
            )
          }
        end

        context 'with deprecated parameters' do
          context 'with default_audit_profile = true' do
            let(:params) { { default_audit_profile: true } }

            it do
              if Puppet[:strict] == :error
                is_expected.to compile.and_raise_error(%r{'auditd::default_audit_profile' is deprecated\.})
              else
                is_expected.to contain_class('auditd::config::audit_profiles')
                is_expected.to contain_class('auditd::config::audit_profiles::simp')
              end
            end
          end

          context 'with default_audit_profile = false' do
            let(:params) { { default_audit_profile: false } }

            it do
              if Puppet[:strict] == :error
                is_expected.to compile.and_raise_error(%r{'auditd::default_audit_profile' is deprecated\.})
              else
                is_expected.to compile.with_all_deps
                is_expected.not_to contain_class('auditd::config::audit_profiles')
                is_expected.not_to contain_class('auditd::config::audit_profiles::simp')
              end
            end
          end

          context "with default_audit_profile = 'simp'" do
            let(:params) { { default_audit_profile: 'simp' } }

            it do
              if Puppet[:strict] == :error
                is_expected.to compile.and_raise_error(%r{'auditd::default_audit_profile' is deprecated\.})
              else
                is_expected.to contain_class('auditd::config::audit_profiles')
                is_expected.to contain_class('auditd::config::audit_profiles::simp')
              end
            end
          end
        end

        context "with default_audit_profiles = 'built_in'" do
          let(:params) { { default_audit_profiles: ['built_in'] } }

          it { is_expected.to contain_class('auditd::config::audit_profiles') }
          it { is_expected.to contain_class('auditd::config::audit_profiles::built_in') }
        end

        # Both auditd major versions are exercised on every OS because the
        # facts are not generated for every supported release. Neither fact is
        # available if auditing in the kernel is not enabled, so the unknown
        # case is covered too.
        [
          { auditd_version: '3.0', auditd_major_version: '3' },
          { auditd_version: '2.4.5', auditd_major_version: '2' },
          { auditd_version: nil, auditd_major_version: nil },
        ].each do |more_facts|
          context "with auditd version #{more_facts[:auditd_major_version].inspect}" do
            let(:facts) do
              f = Marshal.load(Marshal.dump(os_facts))
              f[:auditd_version] = more_facts[:auditd_version]
              f[:auditd_major_version] = more_facts[:auditd_major_version]
              f
            end

            # auditd.conf is edited key by key with ini_setting rather than
            # rendered from a template, so assert the managed keys directly.
            # Any key absent from this hash keeps the value the audit package
            # shipped -- that is the point of the ini_setting approach.
            let(:expected_settings) do
              settings = {
                'log_file' => '/var/log/audit/audit.log',
                'log_format' => 'raw',
                'log_group' => 'root',
                'priority_boost' => 4,
                'flush' => 'incremental',
                'freq' => 20,
                'num_logs' => 5,
                'name_format' => 'USER',
                'name' => facts[:networking][:fqdn],
                'max_log_file' => 24,
                'max_log_file_action' => 'rotate',
                'space_left' => 80,
                'space_left_action' => 'syslog',
                'admin_space_left' => 50,
                'admin_space_left_action' => 'rotate',
                'disk_full_action' => 'rotate',
                'disk_error_action' => 'syslog',
                'write_logs' => 'yes',
                'local_events' => 'yes',
                'verify_email' => 'yes',
                'overflow_action' => 'SYSLOG',
                'q_depth' => 160,
                'max_restarts' => 10,
                'plugin_dir' => '/etc/audit/plugins.d',
                'action_mail_acct' => 'root',
              }

              if more_facts[:auditd_major_version] == '2'
                # auditd < 2.5.2 leaves $auditd::_write_logs unset, so the key
                # is not managed at all, and the version-2 Hiera layer puts the
                # plugin directory somewhere else.
                settings.delete('write_logs')
                settings['plugin_dir'] = '/etc/audisp/plugins.d'
              end

              settings
            end

            context 'with default parameters' do
              let(:params) { {} }

              # The declaration for auditd.conf exists to enforce attributes and
              # to keep the recurse/purge on /etc/audit from deleting the file.
              # It must never manage contents, or every vendor key this module
              # has no opinion about would be lost.
              it { is_expected.to contain_file('/etc/audit/auditd.conf').with(owner: 'root', group: 'root', mode: 'u+rwX,g-rwx,o-rwx') }
              it { is_expected.to contain_file('/etc/audit/auditd.conf').without_content }
              it { is_expected.to contain_file('/etc/audit/auditd.conf').without_source }

              it {
                expected_settings.each do |setting, value|
                  is_expected.to contain_ini_setting("auditd.conf #{setting}").with(
                    path: '/etc/audit/auditd.conf',
                    section: '',
                    setting: setting,
                    value: value,
                  )
                end
              }

              # The keys the auditd 2.x template used to write are gone. No
              # supported OS ships an auditd old enough to want them.
              it { is_expected.not_to contain_ini_setting('auditd.conf disp_qos') }
              it { is_expected.not_to contain_ini_setting('auditd.conf dispatcher') }
            end

            context 'with syslog enabled' do
              let(:params) { { syslog: true } }

              it { is_expected.to contain_class('auditd::config::logging').that_notifies('Class[auditd::service]') }
              # Test private class config::logging
              it {
                if facts[:auditd_version].nil? || facts[:auditd_major_version] >= '3'
                  is_expected.not_to contain_class('auditd::config::audisp')
                else
                  is_expected.to contain_class('auditd::config::audisp')
                end
              }
              # Configured even before auditd_version is known: a missing
              # fact is treated as audit 3 (see auditd::config::logging).
              it { is_expected.to contain_class('auditd::config::audisp::syslog') }
            end
          end # End auditd version context
        end # End auditd version loop
      end # End OS Context
    end # End OS loop
  end
end
