# NOTE: THIS IS A [PRIVATE](https://github.com/puppetlabs/puppetlabs-stdlib#assert_private) CLASS**
#
# @summary This class is called from auditd for service config.
#
# @author https://github.com/simp/pupmod-simp-auditd/graphs/contributors
#
class auditd::config {
  assert_private()

  if $auditd::default_audit_profile != undef {
    deprecation('auditd::default_audit_profile',
    "'auditd::default_audit_profile' is deprecated. Use 'auditd::default_audit_profiles' instead")
    if $auditd::default_audit_profile {
      $profiles = ['simp']
    } else {
      $profiles = []
    }
  } else {
    $profiles = $auditd::default_audit_profiles
  }

  # config_group is unset unless a site asks for one. The rule files this module
  # writes still need a group, and CIS 6.3.4.7 wants 'root' specifically, so
  # that is the fallback -- it is also what the package already ships.
  $_config_group = pick($auditd::config_group, 'root')

  $config_file_mode = $_config_group ? {
    'root'  => 'u+rwX,g-rwx,o-rwx',
    default => 'u+rwX,g+rX,g-w,o-rwx'
  }

  $log_file_mode = $auditd::log_group ? {
    'root'  => 'u+rX,g-rwx,o-rwx',
    default => 'u+rX,g+rX,g-w,o-rwx'
  }

  # Ownership and permissions for every file this module drops into
  # /etc/audit/rules.d. Those files are declared explicitly (they carry
  # content/source), so a recurse on File['/etc/audit/rules.d'] cannot manage
  # them: Puppet discards a recursion-generated child whenever an explicit
  # resource already exists for that path. Without this, the files keep whatever
  # group they were created with -- root's primary group, which is not always
  # 'root' -- and Puppet never repairs it (CIS 6.3.4.6/6.3.4.7).
  #
  # Splat this into each rules.d file resource rather than repeating the
  # attributes, so a new rules file cannot silently omit them. Enforcing them
  # is idempotent because augenrules only reads rules.d; it rewrites
  # /etc/audit/audit.rules instead (see the $audit_rules_* parameters).
  #
  # Note that CIS 6.3.4.7 wants a group owner of 'root' specifically, so a site
  # that sets $config_group to a non-root group trades that rule away here.
  $rule_file_attributes = {
    'owner' => 'root',
    'group' => $_config_group,
    'mode'  => $config_file_mode,
  }

  # Declared only when it has work to do: purging rule files this module does
  # not manage, or giving the rule files it does write their owner/group/mode.
  # The package already ships this directory, so a bare include of auditd has no
  # reason to touch it.
  if $auditd::purge_auditd_rules or !empty($profiles) {
    file { '/etc/audit/rules.d':
      ensure  => 'directory',
      owner   => 'root',
      group   => $_config_group,
      mode    => $config_file_mode,
      recurse => $auditd::purge_auditd_rules,
      purge   => $auditd::purge_auditd_rules,
      force   => $auditd::purge_auditd_rules,
      require => Package[$auditd::package_name],
    }
  }

  # /etc/audit/audit.rules and .prev are generated by augenrules from the rules
  # in /etc/audit/rules.d. augenrules rewrites them (as root:root, mode 0640)
  # each time auditd loads its rules, so enforcing permissions here fights
  # augenrules: Puppet resets them every run, which refreshes auditd::config ->
  # restarts the service -> regenerates the files -> repeat, breaking
  # idempotency (observed on EL8).
  #
  # They are therefore declared only when a site explicitly asks for one of the
  # audit_rules_* attributes and accepts that trade. Previously they were always
  # declared, because an explicit resource was the only way to shield a path
  # from the recurse/purge this class used to run over all of /etc/audit; that
  # purge is gone, and with it the reason to declare these unconditionally.
  $_audit_rules_attributes = {
    'owner' => $auditd::audit_rules_owner,
    'group' => $auditd::audit_rules_group,
    'mode'  => $auditd::audit_rules_mode,
  }.filter |$attribute, $value| { $value =~ NotUndef }

  unless empty($_audit_rules_attributes) {
    file { [
        '/etc/audit/audit.rules',
        '/etc/audit/audit.rules.prev'
      ]:
        require => Package[$auditd::package_name],
        *       => $_audit_rules_attributes,
    }
  }

  # auditd.conf's contents are edited in place by the ini_setting resources
  # below. This resource exists purely to enforce ownership and permissions, so
  # it is declared only when a site asks for a group on it -- the package
  # already ships the file root:root 0640.
  #
  # It deliberately carries no content or source: the file's contents are left
  # to the package and the ini_settings.
  if $auditd::config_group {
    file { '/etc/audit/auditd.conf':
      owner => 'root',
      group => $auditd::config_group,
      mode  => $config_file_mode,
    }

    $_auditd_conf_require = [Package[$auditd::package_name], File['/etc/audit/auditd.conf']]
  }
  else {
    $_auditd_conf_require = [Package[$auditd::package_name]]
  }

  # The audit package ships a complete auditd.conf. Rather than overwrite it
  # wholesale -- which silently reverts every key this module has no opinion
  # about to auditd's compiled-in default -- edit only the keys we manage and
  # leave the rest of the vendor file intact.
  #
  # section => '' addresses the region above any [section] header. auditd.conf
  # has no headers at all, so that region is the entire file.
  $_auditd_conf_defaults = {
    'path'              => '/etc/audit/auditd.conf',
    'section'           => '',
    'key_val_separator' => ' = ',
    'require'           => $_auditd_conf_require,
    'notify'            => Class['auditd::service'],
  }

  # Every key below is undef unless a site sets it, and undef keys are filtered
  # out rather than written. This is the blast-radius change: these used to be
  # written on every run, from module data, whether or not anyone had asked.
  $_auditd_conf_base = {
    'log_file'                => $auditd::log_file,
    'log_format'              => $auditd::_log_format,
    'log_group'               => $auditd::log_group,
    'priority_boost'          => $auditd::priority_boost,
    'flush'                   => $auditd::flush,
    'freq'                    => $auditd::freq,
    'num_logs'                => $auditd::num_logs,
    'max_log_file'            => $auditd::max_log_file,
    'max_log_file_action'     => $auditd::max_log_file_action,
    'space_left'              => $auditd::space_left,
    'space_left_action'       => $auditd::space_left_action,
    'admin_space_left'        => $auditd::admin_space_left,
    'admin_space_left_action' => $auditd::admin_space_left_action,
    'disk_full_action'        => $auditd::disk_full_action,
    'disk_error_action'       => $auditd::disk_error_action,
    'action_mail_acct'        => $auditd::action_mail_acct,
  }

  # name is what a name_format of USER resolves to, so the two are written
  # together or not at all. Writing name on its own does nothing, and writing
  # name_format => 'USER' without a name leaves auditd with no node name.
  if $auditd::name_format =~ NotUndef {
    $_auditd_conf_name = {
      'name_format' => $auditd::name_format,
      'name'        => $auditd::lname,
    }
  }
  else {
    $_auditd_conf_name = {}
  }

  # $auditd::_write_logs is left unset on auditd < 2.5.2, where a log_format of
  # NOLOG carried the same meaning. Preserve that guard.
  if defined('$auditd::_write_logs') {
    $_auditd_conf_write_logs = {
      'write_logs' => $auditd::_write_logs ? { undef => undef, false => 'no', default => 'yes' },
    }
  }
  else {
    $_auditd_conf_write_logs = {}
  }

  # auditd 3.0+ keys.
  #
  # plugin_dir is written only when a site sets it. Its default is the package's
  # own value, so writing it then would change nothing -- but this module also
  # places syslog.conf in it, and a custom directory auditd was never told about
  # is a plugin that silently never loads.
  $_auditd_conf_v3 = {
    'local_events'    => $auditd::local_events ? { undef => undef, false => 'no', default => 'yes' },
    'verify_email'    => $auditd::verify_email ? { undef => undef, false => 'no', default => 'yes' },
    'plugin_dir'      => $auditd::plugin_dir,
    'overflow_action' => $auditd::overflow_action,
    'q_depth'         => $auditd::q_depth,
    'max_restarts'    => $auditd::max_restarts,
  }

  # undef means "leave whatever the package shipped". An ini_setting with an
  # undef value would write a keyword with an empty value, which is not valid
  # auditd.conf syntax, so drop the key instead.
  $_auditd_conf = (
    $_auditd_conf_base + $_auditd_conf_name + $_auditd_conf_write_logs + $_auditd_conf_v3
  ).filter |$setting, $value| {
    $value =~ NotUndef
  }

  $_auditd_conf.each |$setting, $value| {
    ini_setting { "auditd.conf ${setting}":
      setting => $setting,
      value   => $value,
      *       => $_auditd_conf_defaults,
    }
  }

  # Only declared when a site asks for a group on the audit logs. The package
  # creates this directory with the ownership and permissions auditd needs.
  if $auditd::log_group {
    file { '/var/log/audit':
      ensure  => 'directory',
      owner   => 'root',
      group   => $auditd::log_group,
      mode    => $log_file_mode,
      recurse => true,
      require => Package[$auditd::package_name],
    }
  }

  if $auditd::syslog {
    include 'auditd::config::logging'
    Class['auditd::config::logging'] ~> Class['auditd::service']
  }

  unless empty($profiles) {
    # use contain instead of include so that config file changes can
    # notify auditd::service class
    contain 'auditd::config::audit_profiles'
  }
}
