# NOTE: THIS IS A [PRIVATE](https://github.com/puppetlabs/puppetlabs-stdlib#assert_private) CLASS**
#
# @summary This class is called from auditd for service config.
#
# @author https://github.com/simp/pupmod-simp-auditd/graphs/contributors
#
class auditd::config {
  assert_private()

  if $auditd::default_audit_profile != undef {
    deprecation('auditd::default_audit_profile',
    "'auditd::default_audit_profile' is deprecated. Use 'auditd::default_audit_profiles' instead")
    if $auditd::default_audit_profile {
      $profiles = ['simp']
    } else {
      $profiles = []
    }
  } else {
    $profiles = $auditd::default_audit_profiles
  }

  $config_file_mode = $auditd::config_group ? {
    'root'  => 'u+rwX,g-rwx,o-rwx',
    default => 'u+rwX,g+rX,g-w,o-rwx'
  }

  $log_file_mode = $auditd::log_group ? {
    'root'  => 'u+rX,g-rwx,o-rwx',
    default => 'u+rX,g+rX,g-w,o-rwx'
  }

  # Ownership and permissions for every file this module drops into
  # /etc/audit/rules.d. Those files are declared explicitly (they carry
  # content/source), so the recurse on File['/etc/audit/rules.d'] below cannot
  # manage them: Puppet discards a recursion-generated child whenever an
  # explicit resource already exists for that path. Without this, the files
  # keep whatever group they were created with -- root's primary group, which
  # is not always 'root' -- and Puppet never repairs it (CIS 6.3.4.6/6.3.4.7).
  #
  # Splat this into each rules.d file resource rather than repeating the
  # attributes, so a new rules file cannot silently omit them. Enforcing them
  # is idempotent because augenrules only reads rules.d; it rewrites
  # /etc/audit/audit.rules instead (see the $audit_rules_* parameters).
  #
  # Note that CIS 6.3.4.7 wants a group owner of 'root' specifically, so a site
  # that sets $config_group to a non-root group trades that rule away here just
  # as it already does for /etc/audit and /etc/audit/auditd.conf.
  #
  # Those resources spell the same triple out longhand below rather than
  # splatting this hash. That is deliberate: this hash is named for rules.d
  # because that is the bug it fixes, and widening it to every /etc/audit
  # resource is a rename ($config_file_attributes) plus a behavior change for
  # files this issue did not touch. If it grows a parameter later, they should
  # be folded in at that point.
  $rule_file_attributes = {
    'owner' => 'root',
    'group' => $auditd::config_group,
    'mode'  => $config_file_mode,
  }

  file { '/etc/audit':
    ensure  => 'directory',
    owner   => 'root',
    group   => $auditd::config_group,
    mode    => $config_file_mode,
    recurse => true,
    purge   => true,
    force   => true,
    require => Package[$auditd::package_name],
  }

  file { '/etc/audit/rules.d':
    ensure  => 'directory',
    owner   => 'root',
    group   => $auditd::config_group,
    mode    => $config_file_mode,
    recurse => true,
    purge   => $auditd::purge_auditd_rules,
    force   => true,
    require => Package[$auditd::package_name],
  }

  # /etc/audit/audit.rules and .prev are generated by augenrules from the
  # rules in /etc/audit/rules.d. augenrules rewrites them (as root:root, mode
  # 0640) each time auditd loads its rules, so enforcing permissions here
  # fights augenrules: Puppet resets them every run, which refreshes
  # auditd::config -> restarts the service -> regenerates the files ->
  # repeat, breaking idempotency (observed on EL8). Their permissions are
  # therefore unmanaged by default (the $audit_rules_* parameters default to
  # undef); a site can opt in to manage them if needed. The explicit
  # declaration still shields the files from the recurse/purge on /etc/audit.
  file { [
      '/etc/audit/audit.rules',
      '/etc/audit/audit.rules.prev'
    ]:
      owner   => $auditd::audit_rules_owner,
      group   => $auditd::audit_rules_group,
      mode    => $auditd::audit_rules_mode,
      require => Package[$auditd::package_name],
  }

  # auditd.conf is edited in place by the ini_setting resources below, but an
  # Ini_setting does NOT shield a path from the recurse/purge on /etc/audit --
  # only a File resource does. Without this declaration Puppet deletes the
  # vendor auditd.conf on every run and the ini_settings recreate a stub
  # holding just the managed keys, losing every key the module has no opinion
  # about. This is the same shield the audit.rules declaration above provides.
  #
  # Deliberately carries no content or source, so the file's contents are left
  # to the package and the ini_settings; only its attributes are enforced.
  file { '/etc/audit/auditd.conf':
    owner => 'root',
    group => $auditd::config_group,
    mode  => $config_file_mode,
  }

  # The audit package ships a complete auditd.conf. Rather than overwrite it
  # wholesale -- which silently reverts every key this module has no opinion
  # about to auditd's compiled-in default -- edit only the keys we manage and
  # leave the rest of the vendor file intact.
  #
  # section => '' addresses the region above any [section] header. auditd.conf
  # has no headers at all, so that region is the entire file.
  $_auditd_conf_defaults = {
    'path'              => '/etc/audit/auditd.conf',
    'section'           => '',
    'key_val_separator' => ' = ',
    'require'           => [Package[$auditd::package_name], File['/etc/audit/auditd.conf']],
    'notify'            => Class['auditd::service'],
  }

  # Written unconditionally, exactly as auditd.conf.epp and
  # auditd.last.conf.epp did.
  $_auditd_conf_base = {
    'log_file'                => $auditd::log_file,
    'log_format'              => $auditd::_log_format,
    'log_group'               => $auditd::log_group,
    'priority_boost'          => $auditd::priority_boost,
    'flush'                   => $auditd::flush,
    'freq'                    => $auditd::freq,
    'num_logs'                => $auditd::num_logs,
    'name_format'             => $auditd::name_format,
    'name'                    => $auditd::lname,
    'max_log_file'            => $auditd::max_log_file,
    'max_log_file_action'     => $auditd::max_log_file_action,
    'space_left'              => $auditd::space_left,
    'space_left_action'       => $auditd::space_left_action,
    'admin_space_left'        => $auditd::admin_space_left,
    'admin_space_left_action' => $auditd::admin_space_left_action,
    'disk_full_action'        => $auditd::disk_full_action,
    'disk_error_action'       => $auditd::disk_error_action,
    'action_mail_acct'        => $auditd::action_mail_acct,
  }

  # $auditd::_write_logs is left unset on auditd < 2.5.2, where a log_format of
  # NOLOG carried the same meaning. Preserve that guard verbatim.
  if defined('$auditd::_write_logs') {
    $_auditd_conf_write_logs = {
      'write_logs' => $auditd::write_logs ? { false => 'no', default => 'yes' },
    }
  } else {
    $_auditd_conf_write_logs = {}
  }

  # auditd 3.0+ keys.
  #
  # local_events and verify_email mirror auditd.3.conf.epp exactly: undef does
  # not match false, so it falls through to 'yes' and the key is always written.
  # The Optional[Boolean] type reads like "undef means leave it alone", but that
  # has never been the behavior. Making undef mean unmanaged is a breaking
  # change and belongs with the rest of the blast-radius work, not here.
  $_auditd_conf_v3 = {
    'local_events'    => $auditd::local_events ? { false => 'no', default => 'yes' },
    'verify_email'    => $auditd::verify_email ? { false => 'no', default => 'yes' },
    'overflow_action' => $auditd::overflow_action,
    'q_depth'         => $auditd::q_depth,
    'max_restarts'    => $auditd::max_restarts,
  }

  # plugin_dir is gated exactly as auditd.3.conf.epp gated it.
  if defined('$auditd::plugin_dir') {
    $_auditd_conf_plugin_dir = { 'plugin_dir' => $auditd::plugin_dir }
  } else {
    $_auditd_conf_plugin_dir = {}
  }

  # The only keys that can still be undef here are overflow_action, q_depth and
  # max_restarts, all of which carry values in data/common.yaml. Reaching this
  # filter means someone set one to undef explicitly, and the templates wrote a
  # keyword with an empty value in that case. Skip the key instead -- an empty
  # value is not valid auditd.conf syntax.
  $_auditd_conf = (
    $_auditd_conf_base + $_auditd_conf_write_logs + $_auditd_conf_v3 + $_auditd_conf_plugin_dir
  ).filter |$setting, $value| {
    $value =~ NotUndef
  }

  $_auditd_conf.each |$setting, $value| {
    ini_setting { "auditd.conf ${setting}":
      setting => $setting,
      value   => $value,
      *       => $_auditd_conf_defaults,
    }
  }

  if defined('$auditd::plugin_dir') {
    file { $auditd::plugin_dir:
      ensure  => 'directory',
      owner   => 'root',
      group   => $auditd::config_group,
      mode    => '0750',
      require => Package[$auditd::package_name],
    }
  }

  file { '/var/log/audit':
    ensure  => 'directory',
    owner   => 'root',
    group   => $auditd::log_group,
    mode    => $log_file_mode,
    recurse => true,
    require => Package[$auditd::package_name],
  }

  if $auditd::syslog {
    include 'auditd::config::logging'
    Class['auditd::config::logging'] ~> Class['auditd::service']
  }

  unless empty($profiles) {
    # use contain instead of include so that config file changes can
    # notify auditd::service class
    contain 'auditd::config::audit_profiles'
  }
}
